//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CWE_MapPatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CWE_MapPatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;Item&gt;Orrin&lt;/Item&gt;
        ///					&lt;Item&gt;Nathaniel&lt;/Item&gt;
        ///					&lt;Item&gt;Cristian&lt;/Item&gt;
        ///					&lt;Item&gt;Ving&lt;/Item&gt;
        ///					&lt;Item&gt;Sarge&lt;/Item&gt;
        ///					&lt;Item&gt;Mardigo&lt;/Item&gt;
        ///					&lt;Item&gt;Maeve&lt;/Item&gt;
        ///					&lt;Item&gt;Brem&lt;/Item&gt;
        /// 
        ///.
        /// </summary>
        internal static string BaseKnightsList {
            get {
                return ResourceManager.GetString("BaseKnightsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;Item&gt;
        ///							&lt;Name/&gt;
        ///							&lt;CaptionFileRef href=&quot;/txt/clan-one-cap.txt&quot;/&gt;
        ///							&lt;ObscureCaptionFileRef href=&quot;/txt/clan-one-cap2.txt&quot;/&gt;
        ///							&lt;DescriptionFileRef href=&quot;/txt/clan-one-desc.txt&quot;/&gt;
        ///							&lt;ProgressCommentsFileRef/&gt;
        ///							&lt;Kind&gt;OBJECTIVE_KIND_SCENARIO_INFO&lt;/Kind&gt;
        ///							&lt;Parameters/&gt;
        ///							&lt;Timeout&gt;-1&lt;/Timeout&gt;
        ///							&lt;Holdout&gt;-1&lt;/Holdout&gt;
        ///							&lt;CheckDelay&gt;-1&lt;/CheckDelay&gt;
        ///							&lt;Dependencies/&gt;
        ///							&lt;InstantVictory&gt;false&lt;/InstantVictory&gt;
        ///							&lt;TargetGlance&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClanOneObjective {
            get {
                return ResourceManager.GetString("ClanOneObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;Item&gt;
        ///							&lt;Name/&gt;
        ///							&lt;CaptionFileRef href=&quot;/txt/clan-two-cap.txt&quot;/&gt;
        ///							&lt;ObscureCaptionFileRef href=&quot;/txt/clan-two-cap2.txt&quot;/&gt;
        ///							&lt;DescriptionFileRef href=&quot;/txt/clan-two-desc.txt&quot;/&gt;
        ///							&lt;ProgressCommentsFileRef/&gt;
        ///							&lt;Kind&gt;OBJECTIVE_KIND_SCENARIO_INFO&lt;/Kind&gt;
        ///							&lt;Parameters/&gt;
        ///							&lt;Timeout&gt;-1&lt;/Timeout&gt;
        ///							&lt;Holdout&gt;-1&lt;/Holdout&gt;
        ///							&lt;CheckDelay&gt;-1&lt;/CheckDelay&gt;
        ///							&lt;Dependencies/&gt;
        ///							&lt;InstantVictory&gt;false&lt;/InstantVictory&gt;
        ///							&lt;TargetGlance&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClanTwoObjective {
            get {
                return ResourceManager.GetString("ClanTwoObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap griffin {
            get {
                object obj = ResourceManager.GetObject("griffin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MTCORSVA {
            get {
                object obj = ResourceManager.GetObject("MTCORSVA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 				&lt;CreaturesUpgradesFilter&gt;
        ///					&lt;ForbiddenBasicUpgradeTiers/&gt;
        ///					&lt;ForbiddenAlterUpgradeTiers/&gt;
        ///					&lt;NotUpgradeable/&gt;
        ///					&lt;ForbiddenUpgrades/&gt;
        ///				&lt;/CreaturesUpgradesFilter&gt;.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///					&lt;Item&gt;RedHeavenHero01&lt;/Item&gt;
        ///					&lt;Item&gt;RedHeavenHero02&lt;/Item&gt;
        ///					&lt;Item&gt;RedHeavenHero03&lt;/Item&gt;
        ///					&lt;Item&gt;RedHeavenHero04&lt;/Item&gt;
        ///					&lt;Item&gt;RedHeavenHero05&lt;/Item&gt;
        ///					&lt;Item&gt;RedHeavenHero06&lt;/Item&gt;
        ///
        ///.
        /// </summary>
        internal static string RedKnightsList {
            get {
                return ResourceManager.GetString("RedKnightsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;Item&gt;
        ///							&lt;Name/&gt;
        ///							&lt;CaptionFileRef href=&quot;/txt/special-paths-objective-cap.txt&quot;/&gt;
        ///							&lt;ObscureCaptionFileRef href=&quot;/txt/special-paths-objective-cap2&quot;/&gt;
        ///							&lt;DescriptionFileRef href=&quot;/txt/special-paths-objective-desc.txt&quot;/&gt;
        ///							&lt;ProgressCommentsFileRef/&gt;
        ///							&lt;Kind&gt;OBJECTIVE_KIND_SCENARIO_INFO&lt;/Kind&gt;
        ///							&lt;Parameters/&gt;
        ///							&lt;Timeout&gt;-1&lt;/Timeout&gt;
        ///							&lt;Holdout&gt;-1&lt;/Holdout&gt;
        ///							&lt;CheckDelay&gt;-1&lt;/CheckDelay&gt;
        ///							&lt;Dependencies/&gt;
        ///							&lt;InstantVictory&gt;false&lt;/Inst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpecialPathsObjective {
            get {
                return ResourceManager.GetString("SpecialPathsObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///						&lt;Item&gt;
        ///							&lt;Name/&gt;
        ///							&lt;CaptionFileRef href=&quot;/txt/rebuild-objective-cap.txt&quot;/&gt;
        ///							&lt;ObscureCaptionFileRef href=&quot;/txt/rebuild-objective-cap2&quot;/&gt;
        ///							&lt;DescriptionFileRef href=&quot;/txt/rebuild-objective-desc.txt&quot;/&gt;
        ///							&lt;ProgressCommentsFileRef/&gt;
        ///							&lt;Kind&gt;OBJECTIVE_KIND_SCENARIO_INFO&lt;/Kind&gt;
        ///							&lt;Parameters/&gt;
        ///							&lt;Timeout&gt;-1&lt;/Timeout&gt;
        ///							&lt;Holdout&gt;-1&lt;/Holdout&gt;
        ///							&lt;CheckDelay&gt;-1&lt;/CheckDelay&gt;
        ///							&lt;Dependencies/&gt;
        ///							&lt;InstantVictory&gt;false&lt;/InstantVictory&gt;
        ///					 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TownRebuildObjective {
            get {
                return ResourceManager.GetString("TownRebuildObjective", resourceCulture);
            }
        }
    }
}
